### ISSUE TITLE
024 other standard identifier

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#59] opened 2021-11-25 00:14 UTC
https://docs.google.com/spreadsheets/d/1svP2Wcpr5z8i4pPyx3QODbmsMSrXBWAQcB60Ku-mSzk/edit#gid=492464001

**Comment by szapoun** [comment] 2022-08-24 07:37
https://docs.google.com/spreadsheets/d/1svP2Wcpr5z8i4pPyx3QODbmsMSrXBWAQcB60Ku-mSzk/edit#gid=492464001

**Comment by szapoun** [comment] 2022-08-24 07:47
I believe that an identifier in a 024 field of a bibliographic record refers to the Manifestation. So, I think that any proposed mappings to Works and Expressions properties are not relevant

**Comment by pan-zhuo** [comment] 2022-08-24 20:42
There's an option in RDA to record the type information before the identifier.

> OPTION (https://access.rdatoolkit.org/en-US_ala-95f6a60f-3d2b-32d8-9486-cf810708d4ba/div_gq5_w5s_dfb)
> Record a value that includes a trade name or the name of an agent who is responsible for assigning the identifier followed by the identifier.

It seems that we will need a boilerplate for formatting identifiers. See discussion #375.

**Comment by szapoun** [comment] 2022-08-25 06:49
Thank you @pan-zhuo for your comment. So, I will revise the mapping to add the name of the agent first. Not sure of the punctuation, but we can discuss this in one of our meetings. 

Have a nice day :)

**Comment by szapoun** [comment] 2022-08-25 07:04
Another issue is $d

In RDA toolkit the property  'rdam:P3004 has identifier for manifestation' defines "024$a, $d" as relevant MARC21B fields. Does this mean that the combination of these two fields should be mapped to the property with a comman in between?
[https://access.rdatoolkit.org/en-US_ala-95f6a60f-3d2b-32d8-9486-cf810708d4ba/d63979f0-0344-4911-a6eb-eae090f7fe8](https://access.rdatoolkit.org/en-US_ala-95f6a60f-3d2b-32d8-9486-cf810708d4ba/d63979f0-0344-4911-a6eb-eae090f7fe87)7"

**Comment by GordonDunsire** [comment] 2022-08-31 14:57
@szapoun: I think it must be $a +delimiter + $d. The M21B manual says $d is numbers to the right of $a (I think they mean numbers that come after the main code). A delimiter other than {nothing} or space is likely, I think, to result in something that is not recognized as the original identifier.

The option mentioned by @pan-zhuo is deliberately fuzzy. RSC was unable to determine, in several specific instances, if the 'name of agent' was part of the identifier or not. For example, an ISSN identifier is always preceded by "ISSN" and it is unclear if this is a) the organization or b) the database of identifiers. It is difficult to determine if ISBN identifiers are prefixed with "ISBN: " because there are variations such as "ISBD-13", etc. The formal technical view is to omit the 'name of agent' if there is any uncertainty, and to use data provenance to record the identifiery system (not the agency!) to which the identifier belongs.

**Comment by cspayne** [comment] 2024-06-22 00:05
@szapoun @GordonDunsire @CECSpecialistI 
We are now minting nomens for these identifiers, but we still need to decide what to do with $d, should it be appended to $a somehow and be part of the nomen string? Or should it just be a note on nomen?

**Comment by GordonDunsire** [comment] 2024-06-24 10:25
@cspayne: The M21B definition of subfield $d is 'Any optional digits carried to the right of the number or code, such as digits provided to identify price, title, or issue information.'. I would now interpret this to mean that the value of subfield $d is not part of the identifier assigned to the manifestation. Instead, it reproduces additional information that is stored elsewhere in the record as a human-readable value. I think the mapping should not include subfield $d, just subfield $a. I think this is confirmed by the example for ind2=1. The standard pattern is:

<manifestation> rdamo:P30004 <nomen> . // has identifier for manifestation
<nomen> rdand:P80068 <024$a> . // has nomen string
<nomen> rdano:P80069 <024 ind1=1-4 or 024$2 when ind1=7> . // has scheme of nomen; value is IRI based on LoC code list

Subfield $d is just dropped. I think none of the other subfields is associated with the nomen-as-identifier. If we take this approach, subfield $z is also dropped; an invalid or cancelled identifier is not in the scheme (that we know of).

**Comment by cspayne** [comment] 2024-06-24 17:04
> Subfield $d is just dropped. I think none of the other subfields is associated with the nomen-as-identifier. If we take this approach, subfield $z is also dropped; an invalid or cancelled identifier is not in the scheme (that we know of).

Our [decision on identifiers](https://github.com/uwlib-cams/MARC2RDA/wiki/Decisions-Index#iin4-add-a-status-for-invalid-identifiers-use-np80168-status-of-identification-2023-06-07-) for $z is to mint a separate nomen with 
rdand:P80168 < http://id.loc.gov/vocabulary/mstatus/cancinv > . // has status of identification

But this doesn't really help with what to do with subfield $d.

My other question is what to do when ind2 = 8 "Unspecified type of standard number or code", is this worth mapping when there's no scheme of nomen?

**Comment by szapoun** [comment] 2024-06-25 06:03
Dear Cypress 
the 024$d definition refers that any digits used in this subfield may be provided to "identify **price**, **title**, or **issue information**".

I cannot perceive this type of info as an identifier. Nor would I use this info in a generic 'note on a manifestation'. Propose to ignore. 

Regarding 1st Ind=8, I searched the relevant vocabulary https://id.loc.gov/vocabulary/identifiers.html and it has no values for "unknown" or "unspecified". So I porpose to just ignore also.

**Comment by GordonDunsire** [comment] 2024-06-25 11:52
@cspayne: When ind1=8, just transform subfield $a  as a string identifier:

{manifestation} rdamd:P30004 '024$a' . // has identifier for manifestation

**Comment by cspayne** [comment] 2024-06-25 15:25
Thank you @GordonDunsire and @szapoun! I have updated the mapping so that $d is not mapped and when ind1=8 $a is a string identifier.

**Closed** 2024-06-26 01:50 UTC
Labels: spreadsheet section assignment, 0XX, coded-rft
