### ISSUE TITLE
542 information relating to copyright status

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#215] opened 2021-11-25 01:45 UTC
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by pennylenger** [comment] 2023-12-13 18:52
@CECSpecialistI  Hi, I have some question about the form. Why are Indicators for subfields D, E, G, I, J, K, N, P, Q  '*', which means it doesn't matter, but for other other subfields, they are separated listed based on the first indicator 'No information provided/private/not private.'"?

**Comment by CECSpecialistI** [comment] 2023-12-20 18:17
Hi Penny,
I am not sure why some subfields are differentiated by private/not private and others are not. Probably the entire field needs to be mapped differently based on the presence of a "private" indicator. Remember that the mappings we are starting with are generated by a mapping script and are not always logical or correct. Does that answer your question?

Crystal

**Comment by lake44me** [comment] 2023-12-20 20:32
@pennylenger @CECSpecialistI  The spreadsheet set-up just assumed there could be a separate mapping for each indicator value, but I believe Crystal is right.  There's another field that has an indicator value of private/not private/no info, it's 561, see the discussion in that issue https://github.com/uwlib-cams/MARC2RDA/issues/225#issuecomment-1284306425  and example.  It's the only case I know of yet where we created a "metadata work" and reified a triple statement in order to give it a category of work -> private statement.  How that could play out with this tag and all its subfields I leave for y'all to figure out :-)

**Comment by lake44me** [comment] 2023-12-20 20:32
oops

**Comment by AdamSchiff** [comment] 2023-12-20 20:58
Deborah,

Here's an record that might be interesting to analyze:

LDR     02987cam a2200589 i 4500
001     99336875201301451
005     20231220124302.0
006     m o d
007     cr bn||||||abp
007     cr bn||||||ada
008     150219t18971897mau o 000 p eng c
019     __ |a 1194123652
035     __ |a (OCoLC)903894204 |z (OCoLC)1194123652
035     __ |a (OCoLC)ocn903894204
040     __ |a OCLCE |b eng |e rda |e pn |c OCLCE |d OCLCQ |d OCLCO |d OCLCA |d HUL |d OCLCQ |d OCLCO |d OCLCL |d NTE |d WAU
041     0_ |3 Lycidas |a eng |h eng
041     1_ |3 Epitaph on Bion |a eng |h grc
042     __ |a dlr |a pcc
046     1_ |3 Lycidas |k 1637 |2 edtf
046     1_ |3 Epitaph on Bion |k -00
049     __ |a WAUW
050     _4 |a PR3558 |b .A1 1897
082     04 |a 821.47
100     1_ |a Milton, John, |d 1608-1674. |1 https://id.oclc.org/worldcat/entity/E39PBJfCxg7wC9qpDcMrCdtFrq
245     10 |a Lycidas / |c by John Milton ; edited by John Phelps Fruit, Ph.D. (Leipsic).
264     _1 |a Boston, U.S.A. ; |a London : |b Ginn & Company, Publishers, |c 1897.
264     _4 |c ©1897
300     __ |a 1 online resource (xvi, 29 pages)
336     __ |a text |b txt |2 rdacontent
337     __ |a computer |b c |2 rdamedia
338     __ |a online resource |b cr |2 rdacarrier
347     __ |a text file |2 rdaft
533     __ |a Electronic reproduction. |b [Place of publication not identified] : |c HathiTrust Digital Library, |d 2015. |5 MiAaHDL
538     __ |a Master and use copy. Digital master created according to Benchmark for Faithful Digital Reproductions of Monographs and Serials, Version 1. Digital Library Federation, December 2002. |u http://purl.oclc.org/DLF/benchrepro0212 |5 MiAaHDL
583     1_ |a digitized |c 2015 |h HathiTrust Digital Library |l committed to preserve |2 pda |5 MiAaHDL
500     __ |a "A verse translation of the Epitaph on Bion is appended for comparative study"--Page vii.
500     __ |a Translation of the Epitaph on Bion is by the Rev. J. Banks [i.e., James Davies].
588     0_ |a Print version record.
505     2_ |a Appendix. The epitaph of Bion, a loving herdsman.
506     __ |3 Use copy |f Restrictions unspecified |2 star |5 MiAaHDL
655     _7 |a Monodies (Poetry) |2 lcgft
655     _7 |a Pastoral elegies. |2 lcgft
730     02 |i Container of (expression): |a Epitaph on Bion. |l English.
776     08 |i Print version: |a Milton, John, 1608-1674. |t Lycidas. |d Boston, U.S.A., London, Ginn & Company, 1897 |w (DLC) 12038206 |w (OCoLC)11886045
740     02 |a Epitaph of Bion, a loving herdsman.
700     1_ |a Fruit, John Phelps, |d 1855-1943, |e editor. |1 https://id.oclc.org/worldcat/entity/E39PCjxmmH8RFcmBRBjXVF48YP
700     1_ |a Davies, James, |d 1820-1883, |e translator. |1 https://id.oclc.org/worldcat/entity/E39PBJqbj7xgd6qVVq38GmjDMP
856     40 |3 HathiTrust Digital Library, Full view |u http://catalog.hathitrust.org/api/volumes/oclc/11886045.html
856     40 |3 New York Public Library |u https://drb-qa.nypl.org/read/3775132
856     40 |3 Google Books |u https://www.google.com/books/edition/Lycidas/c5Axa_z4HQYC
856     40 |3 Google Books |u https://books.google.com/books?id=c5Axa_z4HQYC
994     __ |a C0 |b WAU


Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by CECSpecialistI** [comment] 2024-08-06 22:57
> @AdamSchiff @GordonDunsire @CECSpecialistI Hello! I have a few questions regarding the mapping for 542:
> 
> 1. MARC documentation says to record "undetermined" if research was done but no value was found (subfields a, d, k, l, m). We've made the decision to not map "unknown" values, does this include "undetermined"? These would be included in a larger note on manifestation and would be contextualized with the subfield label, so it would be indicating that research was done but no information was available. Do we map these?
> 2. Subfield f - copyright statement is defined as "copyright statement as it is presented on the resource." and is currently (perhaps incorrectly) mapped to "has manifestation copyright statement". I was reviewing old meeting notes/recordings and it seems that we have decided not to use any manifestation statement properties, as we don't have access to the original source material. Am I understanding that correctly? Should this mapping be changed to "has note on manifestation"?
> 3. For date subfields (g, i, j) does the transform need to account for any possible punctuation like we do with 264, such as square brackets and copyright symbols and remove those?

1. I think that since these are notes, it's fine to map values of "undetermined" in this context. 
2. I think Subfield f is an exact mapping to has manifestation copyright statement. This is the copyright statement as it appears on the original source material, in this case, so we do have access to the original source material. 
3. Copyright symbols are present, at least. I'm not sure about square brackets or any other punctuation. If we're recording values as unstructured descriptions, I think they are ok the way they are. If we were recording timespans and using a specific SES we may need to make changes.

**Comment by GordonDunsire** [comment] 2024-08-07 10:22
@cspayne:

1. Agree with @CECSpecialistI.

2: Agree with @CECSpecialistI. 

3. It's a note, so there is no need to remove anything.

**Comment by CECSpecialistI** [comment] 2024-08-28 00:35
is the code still on hold here? I think we should be ok.

**Comment by cspayne** [comment] 2024-08-28 00:44
@CECSpecialistI 
I think we are good. I have not removed "code on hold" because I have not gone in to update the code yet.

**Closed** 2024-09-10 17:46 UTC
Labels: spreadsheet section assignment, 5XX, coded-rft
